Numpy

Numpay is a fundamental library for scientific computing in python. it provides support for arrays and matrics, along with a collection of mathematical functions to operate on these data structures. in this lesson, we will cover the basic of Numpy, focusing on arrays and vectorized operations.


In [1]:
!pip install numpy


In [2]:
import numpy as np
## create array using numpy
## create a 1D arrray
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print("Shape of arr1:",arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Shape of arr1: (5,)


In [7]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)     ## 1 row and 6 columns
arr2.reshape(2,3)     ## 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2.shape
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
np.arange(0,10,2)   ## it will create array from 0 to 9
  ## it will create array from 0 to 14 with step size 3


array([0, 2, 4, 6, 8])

In [19]:
np.arange(0,15,3).reshape(5,1) 

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12]])

In [20]:
np.ones((3,4))  ## it will create 3 rows and 4 columns with all values as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
## identity matrix
np.eye(4)  ## it will create 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
## Attribute of numpy array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)
print("Shape of array:",arr.shape)
print("Number of dimensions:",arr.ndim)     
print("Size of array:",arr.size)
print("Data type of array elements:",arr.dtype) 
print("Item size in bytes:",arr.itemsize)
print("Total bytes consumed by the array:",arr.nbytes)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of array: (3, 3)
Number of dimensions: 2
Size of array: 9
Data type of array elements: int64
Item size in bytes: 8
Total bytes consumed by the array: 72


In [25]:
## vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50]) 
##element wise addition
print("Addition:",arr1+arr2)
## element wise subtraction 
print("Subtraction:",arr2-arr1)
## element wise multiplication  
print("Multiplication:",arr1*arr2)
## element wise division
print("Division:",arr2/arr1)
## scalar operations
print("Scalar Addition:",arr1+5)
print("Scalar Multiplication:",arr2*2)
## universal functions
print("Square root of arr1:",np.sqrt(arr1))
print("Exponential of arr2:",np.exp(arr2))
print("Sine of arr1:",np.sin(arr1))
print("Logarithm of arr2:",np.log(arr2))
## indexing and slicing
arr=np.array([10,20,30,40,50,60,70,80
])
print("Original array:",arr)
print("Element at index 3:",arr[3])
print("Elements from index 2 to 5:",arr[2:6])
print("Elements from start to index 4:",arr[:5])
print("Elements from index 4 to end:",arr[4:])
## 2D array indexing and slicing
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original 2D array:\n",arr2d)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Scalar Addition: [ 6  7  8  9 10]
Scalar Multiplication: [ 20  40  60  80 100]
Square root of arr1: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of arr2: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Sine of arr1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm of arr2: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Original array: [10 20 30 40 50 60 70 80]
Element at index 3: 40
Elements from index 2 to 5: [30 40 50 60]
Elements from start to index 4: [10 20 30 40 50]
Elements from index 4 to end: [50 60 70 80]
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
## array indexing and sclinging

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
arr[0][0]

np.int64(1)

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr[0]

array([1, 2, 3])

In [33]:
arr[1:2,1:3]

array([[5, 6]])

In [34]:
arr[1:,2:]

array([[6],
       [9]])

In [36]:
arr[0,0]=100
print(arr)


[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [37]:
arr[1:]=100

In [38]:
print(arr)


[[100   2   3]
 [100 100 100]
 [100 100 100]]


In [40]:
### statistical cocepts -- normalization
## to have a mean of a 0 and standard deviation of 1
data =np.array([10,20,30,40,50])
mean = np.mean([1,2,3,4,5])
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev   
print("Normalized data:",normalized_data)

Normalized data: [0.49497475 1.20208153 1.90918831 2.61629509 3.32340187]


In [41]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#mean
mean = np.mean(data)
print("Mean:",mean)

# median
median = np.median(data)    
print("Median:",median)

# standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)
# variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [44]:
## logical operations
data = np.array([10,20,30,40,50])
print(data > 25)    
print(data <= 30)
print(data == 40)  
print(data != 20)
print(data < 30)
print(data [data < 30])

[False False  True  True  True]
[ True  True  True False False]
[False False False  True False]
[ True False  True  True  True]
[ True  True False False False]
[10 20]
